server:
  servlet:
    context-path: /student/management/v1
  port: 8080
config:
  teacher-service:
    url:
spring:
  Kafka:
    bootstrap-servers=localhost: 9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

